class RecipeModel {
  final String name;
  final String image;
  final String category;
  final String duration;
  final String serving;
  final List<String> ingredients;
  final List<String> instructions;
  final List<String> cook;
  final List<String> optionalAdditions;
  final List<String> serve;

  RecipeModel({
    required this.name,
    required this.image,
    required this.category,
    required this.duration,
    required this.serving,
    required this.ingredients,
    required this.instructions,
    required this.optionalAdditions,
    required this.cook,
    required this.serve,
  });
}

// Sample data
final trandingRecipes = [
  RecipeModel(
    name: "Shrimp Sushi Bowls",
    image: "assets/shrimp_sushi_bowls.jpeg",
    category: "Seafood",
    duration: "1 Hour",
    serving: "2 Seving",
    ingredients: [
      '2 cups sushi rice',
      '1/4 cup rice vinegar',
      '2 tablespoons sugar',
      '1 teaspoon salt',
      '1 pound shrimp, peeled and deveined',
      '2 tablespoons soy sauce',
      '1 tablespoon sesame oil',
      '1 tablespoon vegetable oil',
      '1 cucumber, thinly sliced',
      '1 avocado, sliced',
      '2 carrots, julienned',
      '1/4 cup pickled ginger',
      '1/4 cup soy sauce (for serving)',
      '2 tablespoons sesame seeds (for garnish)',
      'Nori sheets, cut into thin strips (optional)',
    ],
    instructions: [
      '1. Prepare Sushi Rice:',
      '   - Rinse sushi rice under cold water until the water runs clear.',
      '   - Cook the rice according to the package instructions.',
      '   - In a small bowl, mix rice vinegar, sugar, and salt. Microwave for 20-30 seconds until sugar dissolves.',
      '   - While the rice is still warm, gently fold in the vinegar mixture. Allow it to cool.',
      '2. Marinate Shrimp:',
      '   - In a bowl, combine shrimp, soy sauce, and sesame oil. Let it marinate for about 10-15 minutes.',
      '   - Heat vegetable oil in a pan over medium-high heat. Cook the shrimp for 2-3 minutes per side or until they turn pink and opaque. Set aside.',
      '3. Assemble Bowls:',
      '   - Divide the sushi rice among serving bowls.',
      '   - Arrange cooked shrimp, cucumber slices, avocado slices, julienned carrots, and pickled ginger on top of the rice.',
      '4. Garnish:',
      '   - Drizzle with additional soy sauce if desired.',
      '   - Garnish with sesame seeds and nori strips.',
    ],
    optionalAdditions: [
      'Add sliced radishes, edamame, or your favorite sushi ingredients.',
      'Serve with wasabi and extra pickled ginger on the side.',
    ],
    cook: ['Total estimated time: 1 hour'],
    serve: ['Serve the Shrimp Sushi Bowls immediately and enjoy!'],
  ),
  RecipeModel(
    name: "Bowl de Salmón crujiente con miel y jengibre",
    image: "assets/crispy_honey_ginger_salmon_bowl.png",
    category: "Mariscos",
    duration: "20 minutos",
    serving: "3 porciones",
    ingredients: [
      '4 filetes de salmón',
      'Sal y pimienta al gusto',
      '2 Cucharadas de aceite de oliva',
      '3 Cucharadas de miel',
      '2 Cucharadas de salsa de soja',
      '1 Cucharadas de genjibre rallado',
      '2 Dientes de ajo, picados',
    ],
    instructions: [
      '1. Precalentar el horno a 200°C.',
      '2. Seque los filetes de salmón con toallas de papel.',
      '3. Sazone ambos lados con sal y pimienta.',
      '4. En un tazón pequeño, mezcle la miel, la salsa de soja, el jengibre rallado y el ajo picado.',
      '5. Caliente el aceite de oliva en una sartén apta para horno a fuego medio-alto.',
      '6. Dorar los filetes de salmón, con la piel hacia abajo, durante 2-3 minutos hasta que la piel esté crujiente',
      '7. Dale la vuelta a los filetes y úntalos con la mezcla de miel y jengibre.',
      '8. Cambie la sartén al horno precalentado y hornee durante unos 10 minutos o hasta que el salmón esté bien cocido y se desmenuce fácilmente con un tenedor.',
      '9. Mientras se hornea el salmón, prepara los componentes de tu tazón.',
      '10. Cocine el arroz integral o la quinua de acuerdo con las instrucciones del envase.',
      '11. Cocine al vapor o ase sus verduras favoritas.',
      '12. Cortar el aguacate en rodajas..',
      '13. Coloque una porción de arroz integral o quinua en cada tazón.',
      '14. Cubra con verduras al vapor / asadas, rodajas de aguacate y un filete de salmón con miel y jengibre.',
    ],
    optionalAdditions: [
      'Agregue rábanos en rodajas, edamame o sus ingredientes favoritos para sushi.',
      'Sirva con wasabi y jengibre en escabeche extra a un lado.',
    ],
    cook: [
      'Tiempo total de cocción: Aproximadamente 15 minutos (10 minutos en el horno y tiempo adicional para la preparación).',
    ],
    serve: [
      '¡Sirve los tazones de salmón crujientes con miel y jengibre inmediatamente y disfruta!',
    ],
  ),
  RecipeModel(
    name: "Grilled Thai Red Curry Shrimp",
    image: "assets/grilled_thai_red_curry_shrimp.jpeg",
    category: "Seafood",
    duration: "1 Hour",
    serving: "2 Seving",
    ingredients: [
      '1 pound shrimp, peeled and deveined',
      '2 tablespoons Thai red curry paste',
      '1 tablespoon fish sauce',
      '1 tablespoon soy sauce',
      '1 tablespoon honey',
      '1 tablespoon vegetable oil',
      '1 tablespoon lime juice',
      '2 cloves garlic, minced',
      'Skewers for grilling',
    ],
    instructions: [
      '1. Marinate Shrimp:',
      '   - Combine shrimp with Thai red curry paste, fish sauce, soy sauce, honey, vegetable oil, lime juice, and minced garlic.',
      '   - Marinate in the refrigerator for at least 30 minutes.',
      '2. Preheat the Grill:',
      '   - Preheat the grill to medium-high heat.',
      '3. Skewer the Shrimp:',
      '   - Thread marinated shrimp onto skewers.',
      '4. Grill the Shrimp:',
      '   - Grill for 2-3 minutes per side until opaque.',
      '   - Baste with remaining marinade during grilling.',
      '5. Optional Additions:',
      '   - Serve with Thai red curry sauce for dipping.',
      '   - Garnish with cilantro and lime wedges.',
      '6. Serve:',
      '   - Remove from the grill and serve hot.',
    ],
    optionalAdditions: [
      'Serve with steamed jasmine rice or rice noodles.',
      'Garnish with chopped fresh cilantro and a squeeze of lime.',
    ],
    cook: [
      'Marination: At least 30 minutes',
      'Grill Time: 2-3 minutes per side',
    ],
    serve: [
      'Serve immediately while hot and flavorful.',
    ],
  ),
  // ... (add more recipes)
];

final latestRecipes = [
  RecipeModel(
    name: "Bowl de Salmón crujiente con miel y jengibre",
    image: "assets/crispy_honey_ginger_salmon_bowl.png",
    category: "Mariscos",
    duration: "20 minutos",
    serving: "3 porciones",
    ingredients: [
      '4 filetes de salmón',
      'Sal y pimienta al gusto',
      '2 Cucharadas de aceite de oliva',
      '3 Cucharadas de miel',
      '2 Cucharadas de salsa de soja',
      '1 Cucharadas de genjibre rallado',
      '2 Dientes de ajo, picados',
    ],
    instructions: [
      '1. Precalentar el horno a 200°C.',
      '2. Seque los filetes de salmón con toallas de papel.',
      '3. Sazone ambos lados con sal y pimienta.',
      '4. En un tazón pequeño, mezcle la miel, la salsa de soja, el jengibre rallado y el ajo picado.',
      '5. Caliente el aceite de oliva en una sartén apta para horno a fuego medio-alto.',
      '6. Dorar los filetes de salmón, con la piel hacia abajo, durante 2-3 minutos hasta que la piel esté crujiente',
      '7. Dale la vuelta a los filetes y úntalos con la mezcla de miel y jengibre.',
      '8. Cambie la sartén al horno precalentado y hornee durante unos 10 minutos o hasta que el salmón esté bien cocido y se desmenuce fácilmente con un tenedor.',
      '9. Mientras se hornea el salmón, prepara los componentes de tu tazón.',
      '10. Cocine el arroz integral o la quinua de acuerdo con las instrucciones del envase.',
      '11. Cocine al vapor o ase sus verduras favoritas.',
      '12. Cortar el aguacate en rodajas..',
      '13. Coloque una porción de arroz integral o quinua en cada tazón.',
      '14. Cubra con verduras al vapor / asadas, rodajas de aguacate y un filete de salmón con miel y jengibre.',
    ],
    optionalAdditions: [
      'Agregue rábanos en rodajas, edamame o sus ingredientes favoritos para sushi.',
      'Sirva con wasabi y jengibre en escabeche extra a un lado.',
    ],
    cook: [
      'Tiempo total de cocción: Aproximadamente 15 minutos (10 minutos en el horno y tiempo adicional para la preparación).',
    ],
    serve: [
      '¡Sirve los tazones de salmón crujientes con miel y jengibre inmediatamente y disfruta!',
    ],
  ),
  // ... (add more recipes)
  RecipeModel(
    name: "Beef Bibimbap with Triple Egg",
    image: "assets/beef_bibimbap_recipe.jpeg",
    category: "Beef",
    duration: "1 Hour",
    serving: "3 Seving",
    ingredients: [
      '1 cup cooked rice',
      '200g beef, thinly sliced',
      '1 carrot, julienned',
      '1 zucchini, julienned',
      '1 cup bean sprouts',
      '3 eggs (1 fried, 2 for poaching)',
      '2 tablespoons vegetable oil',
      '2 tablespoons soy sauce',
      '1 tablespoon sesame oil',
      'Salt and pepper to taste',
      'Sesame seeds for garnish',
      'Optional: Gochujang (Korean red pepper paste) for extra spice',
    ],
    instructions: [
      '1. Prepare the Rice:',
      '   - Cook rice according to package instructions. Set aside.',
      '',
      '2. Cook the Beef:',
      '   - Heat 1 tablespoon of vegetable oil in a pan over medium heat.',
      '   - Add thinly sliced beef to the pan.',
      '   - Season with salt and pepper, and cook until browned and cooked through.',
      '   - Drizzle with soy sauce and sesame oil. Mix well.',
      '',
      '3. Prepare Vegetables:',
      '   - In the same pan, add another tablespoon of vegetable oil.',
      '   - Stir-fry julienned carrots and zucchini until slightly tender.',
      '   - Blanch bean sprouts in boiling water for a minute. Drain.',
      '',
      '4. Fry the Eggs:',
      '   - Fry one egg sunny-side-up until the yolk is cooked to your liking.',
      '',
      '5. Poach the Eggs:',
      '   - Bring a pot of water to a gentle simmer.',
      '   - Crack two eggs into the simmering water and poach until whites are set but yolks are still runny.',
      '',
      '6. Assemble the Bibimbap:',
      '   - In a serving bowl, place a portion of cooked rice.',
      '   - Arrange cooked beef, sautéed vegetables, and poached eggs on top of the rice.',
      '',
      '7. Garnish:',
      '   - Place the fried egg on one side of the bowl.',
      '   - Sprinkle sesame seeds over the dish.',
      '',
    ],
    optionalAdditions: [
      '   - Kimchi',
      '   - Sliced cucumbers',
      '   - Shredded nori (seaweed)',
    ],
    cook: [
      '   - Approximately 30-40 minutes',
    ],
    serve: [
      '    - Serve the Beef Bibimbap with Triple Egg immediately.',
      '   - Optionally, add a dollop of Gochujang for extra flavor.',
    ],
  ),
  RecipeModel(
    name: "Grilled Chicken Salad + Homemade Sweet Onion Dressing",
    image: "assets/grilled_chicken_salad.jpeg",
    category: "Chicken",
    duration: "1 Hour",
    serving: "2 Seving",
    ingredients: [
      'Grilled Chicken Breast',
      'Mixed Salad Greens (lettuce, spinach, arugula, etc.)',
      'Cherry Tomatoes, halved',
      'Cucumber, sliced',
      'Red Onion, thinly sliced',
      'Avocado, sliced',
      'Feta Cheese, crumbled (optional)',
      'Olive Oil',
      'Salt and Pepper to taste',
    ],
    instructions: [
      '1. Grill the Chicken Breast:',
      '   - Season the chicken breast with salt and pepper.',
      '   - Grill until fully cooked with a nice char. Let it rest and slice into strips.',
      '2. Prepare the Salad:',
      '   - Combine mixed salad greens, cherry tomatoes, cucumber, red onion, and avocado.',
      '3. Assemble the Salad:',
      '   - Add grilled chicken strips on top of the salad.',
      '4. Make the Homemade Sweet Onion Dressing:',
      '   - In a bowl, whisk together olive oil, red wine vinegar, Dijon mustard, honey, and minced sweet onion.',
      '   - Season with salt and pepper.',
      '5. Drizzle Dressing Over Salad:',
      '   - Pour the dressing over the salad.',
    ],
    optionalAdditions: [
      '   - Sprinkle crumbled feta cheese on top for extra flavor.',
    ],
    cook: [
      'Grilling Chicken: Approximately 15-20 minutes',
      'Assembling and preparing salad: 10 minutes',
      'Making the dressing: 5 minutes',
    ],
    serve: [
      'Toss the salad gently to coat. Serve immediately.',
      'Serve the Grilled Chicken Salad as a refreshing and nutritious main course.',
    ],
  ),
];
